version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    reviewers:
      - "yourusername"
      - "python-experts"
    assignees:
      - "yourusername"
    labels:
      - "dependencies"
      - "python"
      - "automated"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      python-dev:
        patterns:
          - "pytest*"
          - "black"
          - "ruff"
          - "mypy"
          - "pre-commit"
      python-minor:
        update-types:
          - "minor"
          - "patch"

  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/rust_core"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "03:00"
    open-pull-requests-limit: 5
    reviewers:
      - "rust-experts"
    labels:
      - "dependencies"
      - "rust"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"
    allow:
      - dependency-type: "all"
    ignore:
      # Ignore specific versions known to have issues
      - dependency-name: "tokio"
        versions: ["1.24.x"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "03:00"
    open-pull-requests-limit: 5
    reviewers:
      - "devops-team"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "03:00"
    open-pull-requests-limit: 3
    reviewers:
      - "devops-team"
    labels:
      - "dependencies"
      - "docker"
      - "automated"
    commit-message:
      prefix: "build"
      include: "scope"

  # NPM (for any JavaScript tooling)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "javascript"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      # Ignore major versions by default
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

# Security updates get priority
security-updates:
  open-pull-requests-limit: 20
  labels:
    - "security"
    - "dependencies"
    - "automated"
    - "priority"
