# Core Python dependencies
python = "^3.10"

# Infrastructure as Code
terraform = "^1.5.0"
ansible = "^8.0.0"
pulumi = "^3.100.0"

# Container Orchestration
kubernetes = "^29.0.0"
docker = "^7.0.0"
helm = "^0.1.0"

# Cloud SDKs
boto3 = "^1.34.0"  # AWS
azure-mgmt = "^4.0.0"  # Azure
google-cloud = "^0.34.0"  # GCP

# API Framework
fastapi = "^0.109.0"
uvicorn = "^0.27.0"
pydantic = "^2.5.0"

# Async Support
asyncio = "^3.4.3"
aiohttp = "^3.9.0"
httpx = "^0.26.0"

# Database
sqlalchemy = "^2.0.0"
alembic = "^1.13.0"
asyncpg = "^0.29.0"
redis = "^5.0.0"

# Monitoring & Logging
prometheus-client = "^0.19.0"
opentelemetry-api = "^1.22.0"
opentelemetry-sdk = "^1.22.0"
structlog = "^24.1.0"

# Security
cryptography = "^42.0.0"
pyjwt = "^2.8.0"
passlib = "^1.7.4"

# Testing
pytest = "^8.0.0"
pytest-asyncio = "^0.23.0"
pytest-cov = "^4.1.0"
pytest-mock = "^3.12.0"

# Development Tools
black = "^24.1.0"
ruff = "^0.1.0"
mypy = "^1.8.0"
pre-commit = "^3.6.0"

# Rust Integration
maturin = "^1.4.0"
pyo3 = "^0.20.0"

# CLI
click = "^8.1.0"
rich = "^13.7.0"
typer = "^0.9.0"

# Data Processing
numpy = "^1.26.0"
pandas = "^2.2.0"
pyyaml = "^6.0.0"

# Natural Language Processing (for NL interface)
langchain = "^0.1.0"
ollama = "^0.1.0"
transformers = "^4.37.0"

# Utilities
python-dotenv = "^1.0.0"
tenacity = "^8.2.0"
cachetools = "^5.3.0"
