apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: synthex-network-policy
  namespace: synthex
spec:
  podSelector:
    matchLabels:
      app: synthex
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: synthex
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 5432
