---
apiVersion: v1
kind: Secret
metadata:
  name: claude-deployment-db-secret
  namespace: claude-deployment
  labels:
    app: claude-deployment
    component: database
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAaG9zdDo1NDMyL2RibmFtZQ==
  username: Y2xhdWRlX3VzZXI=
  password: c3VwZXJfc2VjdXJlX3Bhc3N3b3Jk
  host: Y2xhdWRlLWRlcGxveW1lbnQtZGI=
  port: NTQzMg==
  database: Y2xhdWRlX2RlcGxveW1lbnQ=

---
apiVersion: v1
kind: Secret
metadata:
  name: claude-deployment-redis-secret
  namespace: claude-deployment
  labels:
    app: claude-deployment
    component: cache
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  redis-url: cmVkaXM6Ly9jbGF1ZGUtZGVwbG95bWVudC1yZWRpczo2Mzc5LzA=
  password: cmVkaXNfc2VjdXJlX3Bhc3N3b3Jk

---
apiVersion: v1
kind: Secret
metadata:
  name: claude-deployment-jwt-secret
  namespace: claude-deployment
  labels:
    app: claude-deployment
    component: auth
type: Opaque
data:
  # Base64 encoded JWT secret - replace with actual value
  jwt-secret: anV0X3N1cGVyX3NlY3VyZV9zZWNyZXRfa2V5XzI1Nl9iaXRz

---
apiVersion: v1
kind: Secret
metadata:
  name: claude-deployment-api-keys
  namespace: claude-deployment
  labels:
    app: claude-deployment
    component: api
type: Opaque
data:
  # Base64 encoded API keys - replace with actual values
  openai-api-key: c2stcHJvai1hYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5eg==
  anthropic-api-key: YW50aHJvcGljX2FwaV9rZXlfYWJjZGVmZ2hpamtsbW5vcA==
  google-api-key: Z29vZ2xlX2FwaV9rZXlfYWJjZGVmZ2hpamtsbW5vcA==

---
apiVersion: v1
kind: Secret
metadata:
  name: claude-deployment-monitoring-secret
  namespace: claude-deployment
  labels:
    app: claude-deployment
    component: monitoring
type: Opaque
data:
  # Base64 encoded monitoring credentials
  grafana-admin-password: Z3JhZmFuYV9hZG1pbl9wYXNzd29yZA==
  prometheus-basic-auth: cHJvbWV0aGV1czpzZWN1cmVfcGFzc3dvcmQ=

---
apiVersion: v1
kind: Secret
metadata:
  name: claude-deployment-tls-certs
  namespace: claude-deployment
  labels:
    app: claude-deployment
    component: tls
type: kubernetes.io/tls
data:
  # Base64 encoded TLS certificate and key
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t...

---
apiVersion: v1
kind: Secret
metadata:
  name: claude-deployment-container-registry
  namespace: claude-deployment
  labels:
    app: claude-deployment
    component: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6InVzZXIiLCJwYXNzd29yZCI6InBhc3MiLCJhdXRoIjoiZFhObGNqcHdZWE56In19fQ==

---
apiVersion: v1
kind: Secret
metadata:
  name: claude-deployment-webhook-secrets
  namespace: claude-deployment
  labels:
    app: claude-deployment
    component: webhooks
type: Opaque
data:
  # Base64 encoded webhook secrets
  github-webhook-secret: Z2l0aHViX3dlYmhvb2tfc2VjcmV0
  slack-webhook-url: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvLi4u
  pagerduty-api-key: cGFnZXJkdXR5X2FwaV9rZXlfc2VjcmV0

---
apiVersion: v1
kind: Secret
metadata:
  name: claude-deployment-backup-credentials
  namespace: claude-deployment
  labels:
    app: claude-deployment
    component: backup
type: Opaque
data:
  # Base64 encoded backup credentials
  aws-access-key-id: QUtJQUlPU0ZPRE5ON0VYQU1QTEU=
  aws-secret-access-key: d0phbFJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ==
  s3-bucket-name: Y2xhdWRlLWRlcGxveW1lbnQtYmFja3Vwcw==
  backup-encryption-key: YmFja3VwX2VuY3J5cHRpb25fa2V5XzI1Nl9iaXRz