name: Feature Request
description: Suggest an idea for CODE
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe alternatives you've considered
      placeholder: Any alternative solutions or features you've considered

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Provide a concrete use case for this feature
      placeholder: How would you use this feature in practice?
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Expected Impact
      description: How important is this feature to you?
      options:
        - Critical - Blocking my use of CODE
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Considerations
      options:
        - label: This feature requires API changes
        - label: This feature requires database changes
        - label: This feature has security implications
        - label: This feature has performance implications
        - label: This is a breaking change

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples