# Security Configuration for Claude Optimized Deployment
# This file defines security policies, standards, and configurations

security_framework:
  version: "1.0.0"
  last_updated: "2025-01-08"
  compliance_standards: ["OWASP", "NIST", "ISO_27001", "CIS"]

# Security Testing Configuration
security_testing:
  static_analysis:
    enabled: true
    tools:
      python:
        - bandit
        - semgrep
        - safety
        - pip-audit
      javascript:
        - eslint-plugin-security
        - npm-audit
        - semgrep
      rust:
        - cargo-audit
        - clippy
        - cargo-deny
    
    thresholds:
      critical: 0
      high: 5
      medium: 20
      low: 50
  
  dynamic_testing:
    enabled: true
    tools:
      - owasp_zap
      - nikto
      - custom_scripts
    
    test_categories:
      - sql_injection
      - xss
      - csrf
      - authentication_bypass
      - authorization_flaws
      - directory_traversal
      - command_injection
  
  dependency_scanning:
    enabled: true
    update_frequency: "daily"
    auto_fix_low_severity: true
    alert_on_new_vulnerabilities: true
  
  penetration_testing:
    enabled: false  # Manual approval required
    frequency: "quarterly"
    scope: ["web_applications", "apis", "network"]

# Security Monitoring Configuration
security_monitoring:
  enabled: true
  
  intrusion_detection:
    enabled: true
    failed_login_threshold: 5
    failed_login_window: 300  # seconds
    suspicious_process_monitoring: true
    network_anomaly_detection: true
  
  file_integrity:
    enabled: true
    monitored_paths:
      - "/etc/passwd"
      - "/etc/shadow"
      - "/etc/hosts"
      - "/etc/ssh/sshd_config"
      - "/usr/bin"
      - "/usr/sbin"
    check_interval: 300  # seconds
  
  log_analysis:
    enabled: true
    log_sources:
      - "/var/log/auth.log"
      - "/var/log/syslog"
      - "/var/log/nginx/access.log"
      - "/var/log/nginx/error.log"
    
    suspicious_patterns:
      - "Failed password for .* from (\\d+\\.\\d+\\.\\d+\\.\\d+)"
      - "Invalid user .* from (\\d+\\.\\d+\\.\\d+\\.\\d+)"
      - "SQL injection attempt"
      - "XSS attempt detected"
  
  alerting:
    email_enabled: false
    slack_enabled: false
    syslog_enabled: true
    webhook_enabled: false
    alert_cooldown: 300  # seconds
    
    severity_thresholds:
      critical: 0
      high: 1
      medium: 5
      low: 10

# Authentication and Authorization
authentication:
  password_policy:
    min_length: 12
    require_uppercase: true
    require_lowercase: true
    require_digits: true
    require_special_chars: true
    max_age_days: 90
    history_size: 12
  
  multi_factor_authentication:
    enabled: true
    required_for_admin: true
    backup_codes: 10
    totp_window: 1
  
  session_management:
    timeout_minutes: 30
    absolute_timeout_hours: 8
    secure_cookies: true
    httponly_cookies: true
    samesite_policy: "Strict"

authorization:
  rbac:
    enabled: true
    default_role: "viewer"
    roles:
      admin:
        permissions: ["read", "write", "delete", "admin"]
        description: "Full system access"
      
      editor:
        permissions: ["read", "write"]
        description: "Content creation and editing"
      
      viewer:
        permissions: ["read"]
        description: "Read-only access"
  
  access_controls:
    principle_of_least_privilege: true
    regular_access_review: true
    review_frequency_days: 90

# Network Security
network_security:
  firewall:
    enabled: true
    default_policy: "deny"
    allowed_ports:
      ssh: 22
      http: 80
      https: 443
    
    rate_limiting:
      enabled: true
      ssh_attempts_per_minute: 6
      http_requests_per_second: 100
  
  ssl_tls:
    min_version: "TLSv1.2"
    cipher_suites: "modern"
    hsts_enabled: true
    hsts_max_age: 31536000  # 1 year
    
    certificate_monitoring:
      expiry_warning_days: 30
      auto_renewal: true

# Infrastructure Security
infrastructure_security:
  system_hardening:
    enabled: true
    
    kernel_parameters:
      ip_forwarding: false
      icmp_redirects: false
      source_routing: false
      log_martians: true
      tcp_syncookies: true
    
    file_permissions:
      strict_permissions: true
      suid_sgid_monitoring: true
      world_writable_monitoring: true
    
    services:
      disable_unnecessary: true
      service_whitelist:
        - "ssh"
        - "nginx"
        - "postgresql"
        - "redis"
  
  container_security:
    enabled: true
    
    image_security:
      vulnerability_scanning: true
      trusted_registries_only: true
      base_image_updates: "weekly"
    
    runtime_security:
      non_root_user: true
      read_only_filesystem: true
      capability_dropping: true
      resource_limits: true
    
    kubernetes_security:
      pod_security_policies: true
      network_policies: true
      rbac_enabled: true
      admission_controllers: true

# Data Protection
data_protection:
  classification:
    enabled: true
    levels:
      - "public"
      - "internal"
      - "confidential"
      - "restricted"
  
  encryption:
    at_rest:
      enabled: true
      algorithm: "AES-256"
      key_rotation_days: 90
    
    in_transit:
      enabled: true
      min_tls_version: "TLSv1.2"
      perfect_forward_secrecy: true
    
    key_management:
      secure_storage: true
      access_logging: true
      key_escrow: false
  
  backup_security:
    encryption_required: true
    offsite_storage: true
    retention_policy_days: 365
    restore_testing: "monthly"

# Incident Response
incident_response:
  enabled: true
  
  team_contacts:
    security_officer: "security@example.com"
    incident_commander: "incident@example.com"
    technical_lead: "tech@example.com"
  
  escalation_matrix:
    low: "4_hours"
    medium: "2_hours"
    high: "1_hour"
    critical: "15_minutes"
  
  response_procedures:
    automated_containment: true
    evidence_preservation: true
    communication_plan: true
    forensic_analysis: true
  
  communication:
    stakeholder_notification: true
    regulatory_reporting: true
    public_disclosure: false  # Case by case basis

# Compliance and Auditing
compliance:
  audit_logging:
    enabled: true
    retention_days: 365
    log_integrity_protection: true
    
    events_to_log:
      - "authentication"
      - "authorization"
      - "data_access"
      - "configuration_changes"
      - "privilege_escalation"
  
  compliance_monitoring:
    enabled: true
    standards:
      owasp_top_10: true
      nist_cybersecurity: true
      iso_27001: true
      cis_controls: true
  
  vulnerability_management:
    scanning_frequency: "weekly"
    remediation_sla:
      critical: "24_hours"
      high: "72_hours"
      medium: "30_days"
      low: "90_days"

# Security Training
security_training:
  mandatory_training: true
  frequency: "annual"
  
  training_modules:
    - "security_awareness"
    - "phishing_prevention"
    - "password_security"
    - "incident_reporting"
    - "secure_coding"  # For developers
    - "system_administration"  # For admins
  
  effectiveness_tracking:
    completion_rates: true
    assessment_scores: true
    simulated_attacks: true

# Security Metrics and KPIs
security_metrics:
  collection_enabled: true
  reporting_frequency: "monthly"
  
  metrics:
    prevention:
      - "vulnerability_scan_coverage"
      - "patch_deployment_time"
      - "security_training_completion"
      - "security_control_effectiveness"
    
    detection:
      - "mean_time_to_detection"
      - "false_positive_rate"
      - "security_event_volume"
      - "threat_intelligence_integration"
    
    response:
      - "mean_time_to_response"
      - "incident_escalation_time"
      - "recovery_time_objective"
      - "business_impact"
    
    governance:
      - "policy_compliance_rate"
      - "audit_finding_closure_time"
      - "risk_assessment_frequency"
      - "security_investment_roi"

# Integration Settings
integrations:
  ci_cd_pipeline:
    security_gates: true
    automated_testing: true
    deployment_approval: true
    rollback_procedures: true
  
  monitoring_tools:
    siem_integration: true
    log_aggregation: true
    alerting_system: true
    dashboard_reporting: true
  
  external_services:
    threat_intelligence_feeds: true
    vulnerability_databases: true
    security_vendors: true
    incident_response_services: false

# Environment-Specific Configurations
environments:
  development:
    security_level: "basic"
    testing_enabled: true
    monitoring_level: "low"
    data_masking: true
  
  staging:
    security_level: "enhanced"
    testing_enabled: true
    monitoring_level: "medium"
    data_masking: true
  
  production:
    security_level: "maximum"
    testing_enabled: true
    monitoring_level: "high"
    data_masking: false
    
    additional_controls:
      - "change_management"
      - "approval_workflows"
      - "enhanced_logging"
      - "real_time_monitoring"

# Automation Settings
automation:
  security_patching:
    enabled: true
    auto_install: "security_updates_only"
    maintenance_window: "02:00-04:00"
    rollback_on_failure: true
  
  threat_response:
    automated_blocking: true
    isolation_procedures: true
    evidence_collection: true
    notification_triggers: true
  
  compliance_checking:
    continuous_monitoring: true
    automated_remediation: true
    policy_enforcement: true
    deviation_alerting: true