[package]
name = "quality-mcp-server"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
tokio = { version = "1.28", features = ["full"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
async-trait = "0.1.68"
futures = "0.3.28"
tracing = "0.1.37"
thiserror = "1.0.40"
anyhow = "1.0.71"
chrono = { version = "0.4.24", features = ["serde"] }
uuid = { version = "1.3.3", features = ["v4", "serde"] }
parking_lot = "0.12.1"
dashmap = "5.4.0"

[lib]
name = "quality_mcp_server"
crate-type = ["rlib"]

[[bin]]
name = "quality-server"
path = "src/bin/server.rs"

[profile.release]
opt-level = 3